import "TravelWindowII.src.OldTurbineUtil.Class"
import "TravelWindowII.src.SettingsManager"
import "TravelWindowII.src.TravelWindow"
import "TravelWindowII.src.TravelListTab"
import "TravelWindowII.src.TravelGridTab"
import "TravelWindowII.src.TravelCaroTab"
import "TravelWindowII.src.TravelPulldownTab"
import "TravelWindowII.src.TravelMapTab"
import "TravelWindowII.src.IndexedDictionary"
import "TravelWindowII.src.TravelDictionary"
import "TravelWindowII.src.SkillData"
import "TravelWindowII.src.LocaleStrings"
import "TravelWindowII.src.LocaleData"
import "TravelWindowII.src.TravelShortcut"
import "TravelWindowII.src.OptionsWindow"
import "TravelWindowII.src.TravelButton"
import "TravelWindowII.src.SettingsMenu"
import "TravelWindowII.src.OptionsPanel"
import "TravelWindowII.src.ChangelogData"
import "TravelWindowII.src.UpdateNotificationWindow"

-- Load tests if test mode is enabled
if Settings and Settings.testMode == 1 then
    import "TravelWindowII.src.TravelTests"
    import "TravelWindowII.src.TestRunner"
end
